#!/bin/bash

COMPOSE_COMMAND="${COMPOSE_COMMAND:-podman-compose}"
#CWD=$(pwd)

start_docker() {
    ${COMPOSE_COMMAND} up -d
}

# Check if the function exists
if declare -f "$1" > /dev/null
then
  # call arguments verbatim
  "$@"
else
  # Run a command against all
  run "$@"
fi
