/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BarChart: typeof import('./src/components/charts/BarChart.vue')['default']
    CollapsableGroup: typeof import('./src/components/CollapsableGroup.vue')['default']
    ControlCreateForm: typeof import('./src/components/catalogs/ControlCreateForm.vue')['default']
    ControlCreateModal: typeof import('./src/components/catalogs/ControlCreateModal.vue')['default']
    DrawIODiagramEditor: typeof import('./src/components/DrawIODiagramEditor.vue')['default']
    FormInput: typeof import('./src/components/forms/FormInput.vue')['default']
    FormTextarea: typeof import('./src/components/forms/FormTextarea.vue')['default']
    GroupCreateForm: typeof import('./src/components/catalogs/GroupCreateForm.vue')['default']
    GroupCreateModal: typeof import('./src/components/catalogs/GroupCreateModal.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LabelList: typeof import('./src/components/LabelList.vue')['default']
    LineChart: typeof import('./src/components/charts/LineChart.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    PageCard: typeof import('./src/components/PageCard.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PageSubHeader: typeof import('./src/components/PageSubHeader.vue')['default']
    PartDisplayEditor: typeof import('./src/components/PartDisplayEditor.vue')['default']
    PrimaryButton: typeof import('./src/components/PrimaryButton.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    ResultComplianceOverTimeChart: typeof import('./src/components/ResultComplianceOverTimeChart.vue')['default']
    ResultStatusBadge: typeof import('./src/components/ResultStatusBadge.vue')['default']
    ResultStatusRing: typeof import('./src/components/ResultStatusRing.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryButton: typeof import('./src/components/SecondaryButton.vue')['default']
    SideNav: typeof import('./src/components/navigation/SideNav.vue')['default']
    SideNavCategory: typeof import('./src/components/navigation/SideNavCategory.vue')['default']
    SideNavLink: typeof import('./src/components/navigation/SideNavLink.vue')['default']
    SideNavLogo: typeof import('./src/components/navigation/SideNavLogo.vue')['default']
    SystemCharacteristicsDiagramGroupForm: typeof import('./src/components/SystemCharacteristicsDiagramGroupForm.vue')['default']
    SystemCharacteristicsForm: typeof import('./src/components/SystemCharacteristicsForm.vue')['default']
    Tabs: typeof import('./src/components/Tabs.vue')['default']
    TertiaryButton: typeof import('./src/components/TertiaryButton.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
