version: '3'

services:
  ui:
    build:
      context: .
      target: 'build'
    tty: true
    volumes:
      - .:/app
      # Prevent our node_modules from being used inside the container.
      - /app/node_modules
    entrypoint: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
