apiVersion: v1
kind: Service
metadata:
  name: ccf-ui-service
  namespace: default
spec:
  selector:
    app: ccf-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
  type: ClusterIP