export const WORKFLOW_IMPORT_MAX_FILES = 10;
export const WORKFLOW_IMPORT_MAX_FILE_SIZE_BYTES = 5 * 1024 * 1024;
export const WORKFLOW_IMPORT_MAX_FILE_SIZE_MB =
  WORKFLOW_IMPORT_MAX_FILE_SIZE_BYTES / 1024 / 1024;
