# Production overrides for ccf-ui
global:
  environment: prod

ui:
  replicaCount: 3
  
  image:
    repository: your-registry.io/ccf/ui
    tag: "1.0.0"
    pullPolicy: Always
  
  service:
    type: ClusterIP
  
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  
  config:
    apiUrl: "https://api.ccf.yourdomain.com"
  
  env:
    NODE_ENV: "production"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: ccf.yourdomain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ccf-ui-tls
      hosts:
        - ccf.yourdomain.com