name: Build and Upload Docker Image

on:
  workflow_call:
    inputs:
      push:
        description: 'Whether the image should be pushed to the repository'
        required: true
        type: boolean
      cache_key:
        description: 'Whether the built image should temporarily be stored'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
          flavor: |
            latest=auto
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=schedule
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: inputs.push
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and cache intermediate (build) stage
        uses: docker/build-push-action@v5
        with:
          target: build
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:build
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: false

      - name: Save `build` image to cache
        if: inputs.cache_key != nil
        run: |
          mkdir -p /tmp/.buildx-cache
          docker save ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:build > /tmp/.buildx-cache/image.tar

      - name: Save Build Cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ inputs.cache_key }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          push: ${{ inputs.push }}
