name: release-please

on:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: release-please

jobs:
  release-please:
    uses: compliance-framework/workflows/.github/workflows/release-please.yml@55c549bf712163152173b398e297fba0f907ceca # v1.4.0
    permissions:
      contents: read
    secrets: inherit
