name: release-please

on:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: release-please

jobs:
  release-please:
    uses: compliance-framework/workflows/.github/workflows/release-please.yml@899dbe5d7dac02de5fd60a92d764b189259e03dd # v1.5.0
    permissions:
      contents: read
    secrets: inherit
